<?xml version="1.0" encoding="ASCII"?>
<grafcet:Grafcet xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:grafcet="http://www.example.org/grafcet" xmlns:terms="http://www.example.org/terms">
  <variableDeclarationContainer>
    <variableDeclarations name="testDummy" variableDeclarationType="internal">
      <sort xsi:type="terms:Integer"/>
    </variableDeclarations>
  </variableDeclarationContainer>
  <partialGrafcets xsi:type="grafcet:PartialGrafcet" name="G1">
    <steps xsi:type="grafcet:Step" id="1" initial="true"/>
    <steps xsi:type="grafcet:Step" id="11"/>
    <steps xsi:type="grafcet:Step" id="111"/>
    <steps xsi:type="grafcet:Step" id="1111"/>
    <steps xsi:type="grafcet:Step" id="11111"/>
    <steps xsi:type="grafcet:Step" id="111111"/>
    <steps xsi:type="grafcet:Step" id="11113"/>
    <steps xsi:type="grafcet:Step" id="11112"/>
    <steps xsi:type="grafcet:Step" id="111121"/>
    <steps xsi:type="grafcet:Step" id="11114"/>
    <steps xsi:type="grafcet:Step" id="1113"/>
    <steps xsi:type="grafcet:Step" id="1112"/>
    <steps xsi:type="grafcet:Step" id="11121"/>
    <steps xsi:type="grafcet:Step" id="111211"/>
    <steps xsi:type="grafcet:Step" id="11123"/>
    <steps xsi:type="grafcet:Step" id="11122"/>
    <steps xsi:type="grafcet:Step" id="111221"/>
    <steps xsi:type="grafcet:Step" id="11124"/>
    <steps xsi:type="grafcet:Step" id="1114"/>
    <steps xsi:type="grafcet:Step" id="113"/>
    <steps xsi:type="grafcet:Step" id="112"/>
    <steps xsi:type="grafcet:Step" id="1121"/>
    <steps xsi:type="grafcet:Step" id="11211"/>
    <steps xsi:type="grafcet:Step" id="112111"/>
    <steps xsi:type="grafcet:Step" id="11213"/>
    <steps xsi:type="grafcet:Step" id="11212"/>
    <steps xsi:type="grafcet:Step" id="112121"/>
    <steps xsi:type="grafcet:Step" id="11214"/>
    <steps xsi:type="grafcet:Step" id="1123"/>
    <steps xsi:type="grafcet:Step" id="1122"/>
    <steps xsi:type="grafcet:Step" id="11221"/>
    <steps xsi:type="grafcet:Step" id="112211"/>
    <steps xsi:type="grafcet:Step" id="11223"/>
    <steps xsi:type="grafcet:Step" id="11222"/>
    <steps xsi:type="grafcet:Step" id="112221"/>
    <steps xsi:type="grafcet:Step" id="11224"/>
    <steps xsi:type="grafcet:Step" id="1124"/>
    <steps xsi:type="grafcet:Step" id="114"/>
    <steps xsi:type="grafcet:Step" id="13"/>
    <steps xsi:type="grafcet:Step" id="12"/>
    <steps xsi:type="grafcet:Step" id="121"/>
    <steps xsi:type="grafcet:Step" id="1211"/>
    <steps xsi:type="grafcet:Step" id="12111"/>
    <steps xsi:type="grafcet:Step" id="121111"/>
    <steps xsi:type="grafcet:Step" id="12113"/>
    <steps xsi:type="grafcet:Step" id="12112"/>
    <steps xsi:type="grafcet:Step" id="121121"/>
    <steps xsi:type="grafcet:Step" id="12114"/>
    <steps xsi:type="grafcet:Step" id="1213"/>
    <steps xsi:type="grafcet:Step" id="1212"/>
    <steps xsi:type="grafcet:Step" id="12121"/>
    <steps xsi:type="grafcet:Step" id="121211"/>
    <steps xsi:type="grafcet:Step" id="12123"/>
    <steps xsi:type="grafcet:Step" id="12122"/>
    <steps xsi:type="grafcet:Step" id="121221"/>
    <steps xsi:type="grafcet:Step" id="12124"/>
    <steps xsi:type="grafcet:Step" id="1214"/>
    <steps xsi:type="grafcet:Step" id="123"/>
    <steps xsi:type="grafcet:Step" id="122"/>
    <steps xsi:type="grafcet:Step" id="1221"/>
    <steps xsi:type="grafcet:Step" id="12211"/>
    <steps xsi:type="grafcet:Step" id="122111"/>
    <steps xsi:type="grafcet:Step" id="12213"/>
    <steps xsi:type="grafcet:Step" id="12212"/>
    <steps xsi:type="grafcet:Step" id="122121"/>
    <steps xsi:type="grafcet:Step" id="12214"/>
    <steps xsi:type="grafcet:Step" id="1223"/>
    <steps xsi:type="grafcet:Step" id="1222"/>
    <steps xsi:type="grafcet:Step" id="12221"/>
    <steps xsi:type="grafcet:Step" id="122211"/>
    <steps xsi:type="grafcet:Step" id="12223"/>
    <steps xsi:type="grafcet:Step" id="12222"/>
    <steps xsi:type="grafcet:Step" id="122221"/>
    <steps xsi:type="grafcet:Step" id="12224"/>
    <steps xsi:type="grafcet:Step" id="1224"/>
    <steps xsi:type="grafcet:Step" id="124"/>
    <steps xsi:type="grafcet:Step" id="14"/>
    <steps xsi:type="grafcet:Step" id="2"/>
    <transitions id="1">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="111">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1111">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11111">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11113">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11112">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11114">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1113">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1112">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11121">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11123">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11122">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11124">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1114">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="113">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="112">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1121">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11211">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11213">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11212">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11214">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1123">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1122">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11221">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11223">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11222">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="11224">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1124">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="114">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="13">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="121">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1211">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12111">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12113">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12112">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12114">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1213">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1212">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12121">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12123">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12122">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12124">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1214">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="123">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="122">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1221">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12211">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12213">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12212">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12214">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1223">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1222">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12221">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12223">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12222">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="12224">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="1224">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="124">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="14">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="2">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <transitions id="3">
      <term xsi:type="terms:BooleanConstant" value="true"/>
    </transitions>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <synchronizations/>
    <arcs source="//@partialGrafcets.0/@steps.0" target="//@partialGrafcets.0/@transitions.0"/>
    <arcs source="//@partialGrafcets.0/@transitions.0" target="//@partialGrafcets.0/@synchronizations.0"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.0" target="//@partialGrafcets.0/@steps.1"/>
    <arcs source="//@partialGrafcets.0/@steps.1" target="//@partialGrafcets.0/@transitions.1"/>
    <arcs source="//@partialGrafcets.0/@transitions.1" target="//@partialGrafcets.0/@synchronizations.2"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.2" target="//@partialGrafcets.0/@steps.2"/>
    <arcs source="//@partialGrafcets.0/@steps.2" target="//@partialGrafcets.0/@transitions.2"/>
    <arcs source="//@partialGrafcets.0/@transitions.2" target="//@partialGrafcets.0/@synchronizations.4"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.4" target="//@partialGrafcets.0/@steps.3"/>
    <arcs source="//@partialGrafcets.0/@steps.3" target="//@partialGrafcets.0/@transitions.3"/>
    <arcs source="//@partialGrafcets.0/@transitions.3" target="//@partialGrafcets.0/@synchronizations.6"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.6" target="//@partialGrafcets.0/@steps.4"/>
    <arcs source="//@partialGrafcets.0/@steps.4" target="//@partialGrafcets.0/@transitions.4"/>
    <arcs source="//@partialGrafcets.0/@transitions.4" target="//@partialGrafcets.0/@steps.5"/>
    <arcs source="//@partialGrafcets.0/@steps.5" target="//@partialGrafcets.0/@transitions.5"/>
    <arcs source="//@partialGrafcets.0/@transitions.5" target="//@partialGrafcets.0/@steps.6"/>
    <arcs source="//@partialGrafcets.0/@steps.6" target="//@partialGrafcets.0/@synchronizations.7"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.6" target="//@partialGrafcets.0/@steps.7"/>
    <arcs source="//@partialGrafcets.0/@steps.7" target="//@partialGrafcets.0/@transitions.6"/>
    <arcs source="//@partialGrafcets.0/@transitions.6" target="//@partialGrafcets.0/@steps.8"/>
    <arcs source="//@partialGrafcets.0/@steps.8" target="//@partialGrafcets.0/@transitions.7"/>
    <arcs source="//@partialGrafcets.0/@transitions.7" target="//@partialGrafcets.0/@steps.9"/>
    <arcs source="//@partialGrafcets.0/@steps.9" target="//@partialGrafcets.0/@synchronizations.7"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.7" target="//@partialGrafcets.0/@transitions.8"/>
    <arcs source="//@partialGrafcets.0/@transitions.8" target="//@partialGrafcets.0/@steps.10"/>
    <arcs source="//@partialGrafcets.0/@steps.10" target="//@partialGrafcets.0/@synchronizations.5"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.4" target="//@partialGrafcets.0/@steps.11"/>
    <arcs source="//@partialGrafcets.0/@steps.11" target="//@partialGrafcets.0/@transitions.9"/>
    <arcs source="//@partialGrafcets.0/@transitions.9" target="//@partialGrafcets.0/@synchronizations.8"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.8" target="//@partialGrafcets.0/@steps.12"/>
    <arcs source="//@partialGrafcets.0/@steps.12" target="//@partialGrafcets.0/@transitions.10"/>
    <arcs source="//@partialGrafcets.0/@transitions.10" target="//@partialGrafcets.0/@steps.13"/>
    <arcs source="//@partialGrafcets.0/@steps.13" target="//@partialGrafcets.0/@transitions.11"/>
    <arcs source="//@partialGrafcets.0/@transitions.11" target="//@partialGrafcets.0/@steps.14"/>
    <arcs source="//@partialGrafcets.0/@steps.14" target="//@partialGrafcets.0/@synchronizations.9"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.8" target="//@partialGrafcets.0/@steps.15"/>
    <arcs source="//@partialGrafcets.0/@steps.15" target="//@partialGrafcets.0/@transitions.12"/>
    <arcs source="//@partialGrafcets.0/@transitions.12" target="//@partialGrafcets.0/@steps.16"/>
    <arcs source="//@partialGrafcets.0/@steps.16" target="//@partialGrafcets.0/@transitions.13"/>
    <arcs source="//@partialGrafcets.0/@transitions.13" target="//@partialGrafcets.0/@steps.17"/>
    <arcs source="//@partialGrafcets.0/@steps.17" target="//@partialGrafcets.0/@synchronizations.9"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.9" target="//@partialGrafcets.0/@transitions.14"/>
    <arcs source="//@partialGrafcets.0/@transitions.14" target="//@partialGrafcets.0/@steps.18"/>
    <arcs source="//@partialGrafcets.0/@steps.18" target="//@partialGrafcets.0/@synchronizations.5"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.5" target="//@partialGrafcets.0/@transitions.15"/>
    <arcs source="//@partialGrafcets.0/@transitions.15" target="//@partialGrafcets.0/@steps.19"/>
    <arcs source="//@partialGrafcets.0/@steps.19" target="//@partialGrafcets.0/@synchronizations.3"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.2" target="//@partialGrafcets.0/@steps.20"/>
    <arcs source="//@partialGrafcets.0/@steps.20" target="//@partialGrafcets.0/@transitions.16"/>
    <arcs source="//@partialGrafcets.0/@transitions.16" target="//@partialGrafcets.0/@synchronizations.10"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.10" target="//@partialGrafcets.0/@steps.21"/>
    <arcs source="//@partialGrafcets.0/@steps.21" target="//@partialGrafcets.0/@transitions.17"/>
    <arcs source="//@partialGrafcets.0/@transitions.17" target="//@partialGrafcets.0/@synchronizations.12"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.12" target="//@partialGrafcets.0/@steps.22"/>
    <arcs source="//@partialGrafcets.0/@steps.22" target="//@partialGrafcets.0/@transitions.18"/>
    <arcs source="//@partialGrafcets.0/@transitions.18" target="//@partialGrafcets.0/@steps.23"/>
    <arcs source="//@partialGrafcets.0/@steps.23" target="//@partialGrafcets.0/@transitions.19"/>
    <arcs source="//@partialGrafcets.0/@transitions.19" target="//@partialGrafcets.0/@steps.24"/>
    <arcs source="//@partialGrafcets.0/@steps.24" target="//@partialGrafcets.0/@synchronizations.13"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.12" target="//@partialGrafcets.0/@steps.25"/>
    <arcs source="//@partialGrafcets.0/@steps.25" target="//@partialGrafcets.0/@transitions.20"/>
    <arcs source="//@partialGrafcets.0/@transitions.20" target="//@partialGrafcets.0/@steps.26"/>
    <arcs source="//@partialGrafcets.0/@steps.26" target="//@partialGrafcets.0/@transitions.21"/>
    <arcs source="//@partialGrafcets.0/@transitions.21" target="//@partialGrafcets.0/@steps.27"/>
    <arcs source="//@partialGrafcets.0/@steps.27" target="//@partialGrafcets.0/@synchronizations.13"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.13" target="//@partialGrafcets.0/@transitions.22"/>
    <arcs source="//@partialGrafcets.0/@transitions.22" target="//@partialGrafcets.0/@steps.28"/>
    <arcs source="//@partialGrafcets.0/@steps.28" target="//@partialGrafcets.0/@synchronizations.11"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.10" target="//@partialGrafcets.0/@steps.29"/>
    <arcs source="//@partialGrafcets.0/@steps.29" target="//@partialGrafcets.0/@transitions.23"/>
    <arcs source="//@partialGrafcets.0/@transitions.23" target="//@partialGrafcets.0/@synchronizations.14"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.14" target="//@partialGrafcets.0/@steps.30"/>
    <arcs source="//@partialGrafcets.0/@steps.30" target="//@partialGrafcets.0/@transitions.24"/>
    <arcs source="//@partialGrafcets.0/@transitions.24" target="//@partialGrafcets.0/@steps.31"/>
    <arcs source="//@partialGrafcets.0/@steps.31" target="//@partialGrafcets.0/@transitions.25"/>
    <arcs source="//@partialGrafcets.0/@transitions.25" target="//@partialGrafcets.0/@steps.32"/>
    <arcs source="//@partialGrafcets.0/@steps.32" target="//@partialGrafcets.0/@synchronizations.15"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.14" target="//@partialGrafcets.0/@steps.33"/>
    <arcs source="//@partialGrafcets.0/@steps.33" target="//@partialGrafcets.0/@transitions.26"/>
    <arcs source="//@partialGrafcets.0/@transitions.26" target="//@partialGrafcets.0/@steps.34"/>
    <arcs source="//@partialGrafcets.0/@steps.34" target="//@partialGrafcets.0/@transitions.27"/>
    <arcs source="//@partialGrafcets.0/@transitions.27" target="//@partialGrafcets.0/@steps.35"/>
    <arcs source="//@partialGrafcets.0/@steps.35" target="//@partialGrafcets.0/@synchronizations.15"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.15" target="//@partialGrafcets.0/@transitions.28"/>
    <arcs source="//@partialGrafcets.0/@transitions.28" target="//@partialGrafcets.0/@steps.36"/>
    <arcs source="//@partialGrafcets.0/@steps.36" target="//@partialGrafcets.0/@synchronizations.11"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.11" target="//@partialGrafcets.0/@transitions.29"/>
    <arcs source="//@partialGrafcets.0/@transitions.29" target="//@partialGrafcets.0/@steps.37"/>
    <arcs source="//@partialGrafcets.0/@steps.37" target="//@partialGrafcets.0/@synchronizations.3"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.3" target="//@partialGrafcets.0/@transitions.30"/>
    <arcs source="//@partialGrafcets.0/@transitions.30" target="//@partialGrafcets.0/@steps.38"/>
    <arcs source="//@partialGrafcets.0/@steps.38" target="//@partialGrafcets.0/@synchronizations.1"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.0" target="//@partialGrafcets.0/@steps.39"/>
    <arcs source="//@partialGrafcets.0/@steps.39" target="//@partialGrafcets.0/@transitions.31"/>
    <arcs source="//@partialGrafcets.0/@transitions.31" target="//@partialGrafcets.0/@synchronizations.16"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.16" target="//@partialGrafcets.0/@steps.40"/>
    <arcs source="//@partialGrafcets.0/@steps.40" target="//@partialGrafcets.0/@transitions.32"/>
    <arcs source="//@partialGrafcets.0/@transitions.32" target="//@partialGrafcets.0/@synchronizations.18"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.18" target="//@partialGrafcets.0/@steps.41"/>
    <arcs source="//@partialGrafcets.0/@steps.41" target="//@partialGrafcets.0/@transitions.33"/>
    <arcs source="//@partialGrafcets.0/@transitions.33" target="//@partialGrafcets.0/@synchronizations.20"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.20" target="//@partialGrafcets.0/@steps.42"/>
    <arcs source="//@partialGrafcets.0/@steps.42" target="//@partialGrafcets.0/@transitions.34"/>
    <arcs source="//@partialGrafcets.0/@transitions.34" target="//@partialGrafcets.0/@steps.43"/>
    <arcs source="//@partialGrafcets.0/@steps.43" target="//@partialGrafcets.0/@transitions.35"/>
    <arcs source="//@partialGrafcets.0/@transitions.35" target="//@partialGrafcets.0/@steps.44"/>
    <arcs source="//@partialGrafcets.0/@steps.44" target="//@partialGrafcets.0/@synchronizations.21"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.20" target="//@partialGrafcets.0/@steps.45"/>
    <arcs source="//@partialGrafcets.0/@steps.45" target="//@partialGrafcets.0/@transitions.36"/>
    <arcs source="//@partialGrafcets.0/@transitions.36" target="//@partialGrafcets.0/@steps.46"/>
    <arcs source="//@partialGrafcets.0/@steps.46" target="//@partialGrafcets.0/@transitions.37"/>
    <arcs source="//@partialGrafcets.0/@transitions.37" target="//@partialGrafcets.0/@steps.47"/>
    <arcs source="//@partialGrafcets.0/@steps.47" target="//@partialGrafcets.0/@synchronizations.21"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.21" target="//@partialGrafcets.0/@transitions.38"/>
    <arcs source="//@partialGrafcets.0/@transitions.38" target="//@partialGrafcets.0/@steps.48"/>
    <arcs source="//@partialGrafcets.0/@steps.48" target="//@partialGrafcets.0/@synchronizations.19"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.18" target="//@partialGrafcets.0/@steps.49"/>
    <arcs source="//@partialGrafcets.0/@steps.49" target="//@partialGrafcets.0/@transitions.39"/>
    <arcs source="//@partialGrafcets.0/@transitions.39" target="//@partialGrafcets.0/@synchronizations.22"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.22" target="//@partialGrafcets.0/@steps.50"/>
    <arcs source="//@partialGrafcets.0/@steps.50" target="//@partialGrafcets.0/@transitions.40"/>
    <arcs source="//@partialGrafcets.0/@transitions.40" target="//@partialGrafcets.0/@steps.51"/>
    <arcs source="//@partialGrafcets.0/@steps.51" target="//@partialGrafcets.0/@transitions.41"/>
    <arcs source="//@partialGrafcets.0/@transitions.41" target="//@partialGrafcets.0/@steps.52"/>
    <arcs source="//@partialGrafcets.0/@steps.52" target="//@partialGrafcets.0/@synchronizations.23"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.22" target="//@partialGrafcets.0/@steps.53"/>
    <arcs source="//@partialGrafcets.0/@steps.53" target="//@partialGrafcets.0/@transitions.42"/>
    <arcs source="//@partialGrafcets.0/@transitions.42" target="//@partialGrafcets.0/@steps.54"/>
    <arcs source="//@partialGrafcets.0/@steps.54" target="//@partialGrafcets.0/@transitions.43"/>
    <arcs source="//@partialGrafcets.0/@transitions.43" target="//@partialGrafcets.0/@steps.55"/>
    <arcs source="//@partialGrafcets.0/@steps.55" target="//@partialGrafcets.0/@synchronizations.23"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.23" target="//@partialGrafcets.0/@transitions.44"/>
    <arcs source="//@partialGrafcets.0/@transitions.44" target="//@partialGrafcets.0/@steps.56"/>
    <arcs source="//@partialGrafcets.0/@steps.56" target="//@partialGrafcets.0/@synchronizations.19"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.19" target="//@partialGrafcets.0/@transitions.45"/>
    <arcs source="//@partialGrafcets.0/@transitions.45" target="//@partialGrafcets.0/@steps.57"/>
    <arcs source="//@partialGrafcets.0/@steps.57" target="//@partialGrafcets.0/@synchronizations.17"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.16" target="//@partialGrafcets.0/@steps.58"/>
    <arcs source="//@partialGrafcets.0/@steps.58" target="//@partialGrafcets.0/@transitions.46"/>
    <arcs source="//@partialGrafcets.0/@transitions.46" target="//@partialGrafcets.0/@synchronizations.24"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.24" target="//@partialGrafcets.0/@steps.59"/>
    <arcs source="//@partialGrafcets.0/@steps.59" target="//@partialGrafcets.0/@transitions.47"/>
    <arcs source="//@partialGrafcets.0/@transitions.47" target="//@partialGrafcets.0/@synchronizations.26"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.26" target="//@partialGrafcets.0/@steps.60"/>
    <arcs source="//@partialGrafcets.0/@steps.60" target="//@partialGrafcets.0/@transitions.48"/>
    <arcs source="//@partialGrafcets.0/@transitions.48" target="//@partialGrafcets.0/@steps.61"/>
    <arcs source="//@partialGrafcets.0/@steps.61" target="//@partialGrafcets.0/@transitions.49"/>
    <arcs source="//@partialGrafcets.0/@transitions.49" target="//@partialGrafcets.0/@steps.62"/>
    <arcs source="//@partialGrafcets.0/@steps.62" target="//@partialGrafcets.0/@synchronizations.27"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.26" target="//@partialGrafcets.0/@steps.63"/>
    <arcs source="//@partialGrafcets.0/@steps.63" target="//@partialGrafcets.0/@transitions.50"/>
    <arcs source="//@partialGrafcets.0/@transitions.50" target="//@partialGrafcets.0/@steps.64"/>
    <arcs source="//@partialGrafcets.0/@steps.64" target="//@partialGrafcets.0/@transitions.51"/>
    <arcs source="//@partialGrafcets.0/@transitions.51" target="//@partialGrafcets.0/@steps.65"/>
    <arcs source="//@partialGrafcets.0/@steps.65" target="//@partialGrafcets.0/@synchronizations.27"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.27" target="//@partialGrafcets.0/@transitions.52"/>
    <arcs source="//@partialGrafcets.0/@transitions.52" target="//@partialGrafcets.0/@steps.66"/>
    <arcs source="//@partialGrafcets.0/@steps.66" target="//@partialGrafcets.0/@synchronizations.25"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.24" target="//@partialGrafcets.0/@steps.67"/>
    <arcs source="//@partialGrafcets.0/@steps.67" target="//@partialGrafcets.0/@transitions.53"/>
    <arcs source="//@partialGrafcets.0/@transitions.53" target="//@partialGrafcets.0/@synchronizations.28"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.28" target="//@partialGrafcets.0/@steps.68"/>
    <arcs source="//@partialGrafcets.0/@steps.68" target="//@partialGrafcets.0/@transitions.54"/>
    <arcs source="//@partialGrafcets.0/@transitions.54" target="//@partialGrafcets.0/@steps.69"/>
    <arcs source="//@partialGrafcets.0/@steps.69" target="//@partialGrafcets.0/@transitions.55"/>
    <arcs source="//@partialGrafcets.0/@transitions.55" target="//@partialGrafcets.0/@steps.70"/>
    <arcs source="//@partialGrafcets.0/@steps.70" target="//@partialGrafcets.0/@synchronizations.29"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.28" target="//@partialGrafcets.0/@steps.71"/>
    <arcs source="//@partialGrafcets.0/@steps.71" target="//@partialGrafcets.0/@transitions.56"/>
    <arcs source="//@partialGrafcets.0/@transitions.56" target="//@partialGrafcets.0/@steps.72"/>
    <arcs source="//@partialGrafcets.0/@steps.72" target="//@partialGrafcets.0/@transitions.57"/>
    <arcs source="//@partialGrafcets.0/@transitions.57" target="//@partialGrafcets.0/@steps.73"/>
    <arcs source="//@partialGrafcets.0/@steps.73" target="//@partialGrafcets.0/@synchronizations.29"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.29" target="//@partialGrafcets.0/@transitions.58"/>
    <arcs source="//@partialGrafcets.0/@transitions.58" target="//@partialGrafcets.0/@steps.74"/>
    <arcs source="//@partialGrafcets.0/@steps.74" target="//@partialGrafcets.0/@synchronizations.25"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.25" target="//@partialGrafcets.0/@transitions.59"/>
    <arcs source="//@partialGrafcets.0/@transitions.59" target="//@partialGrafcets.0/@steps.75"/>
    <arcs source="//@partialGrafcets.0/@steps.75" target="//@partialGrafcets.0/@synchronizations.17"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.17" target="//@partialGrafcets.0/@transitions.60"/>
    <arcs source="//@partialGrafcets.0/@transitions.60" target="//@partialGrafcets.0/@steps.76"/>
    <arcs source="//@partialGrafcets.0/@steps.76" target="//@partialGrafcets.0/@synchronizations.1"/>
    <arcs source="//@partialGrafcets.0/@synchronizations.1" target="//@partialGrafcets.0/@transitions.61"/>
    <arcs source="//@partialGrafcets.0/@transitions.61" target="//@partialGrafcets.0/@steps.77"/>
    <arcs source="//@partialGrafcets.0/@steps.77" target="//@partialGrafcets.0/@transitions.62"/>
    <arcs source="//@partialGrafcets.0/@transitions.62" target="//@partialGrafcets.0/@steps.0"/>
  </partialGrafcets>
</grafcet:Grafcet>
